# Generated by Django 5.0.14 on 2025-06-08 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_asignacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(help_text='ID del producto afectado')),
                ('codigo_material', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=200, null=True)),
                ('accion', models.CharField(choices=[('crear', 'Producto Creado'), ('editar', 'Producto Editado'), ('eliminar', 'Producto Eliminado'), ('stock_entrada', 'Entrada de Stock'), ('stock_salida', 'Salida de Stock'), ('asignacion', 'Producto Asignado'), ('devolucion', 'Producto Devuelto')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción')),
                ('cantidad_anterior', models.IntegerField(blank=True, null=True)),
                ('cantidad_nueva', models.IntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior del producto', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo del producto', null=True)),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_producto',
                'ordering': ['-fecha_accion'],
            },
        ),
        #migrations.DeleteModel(
        #    name='MovimientoInventario',
        #),
        migrations.AddIndex(
            model_name='auditoriaproducto',
            index=models.Index(fields=['producto_id'], name='auditoria_p_product_f5c5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaproducto',
            index=models.Index(fields=['accion'], name='auditoria_p_accion_fd4edd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaproducto',
            index=models.Index(fields=['fecha_accion'], name='auditoria_p_fecha_a_04fbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaproducto',
            index=models.Index(fields=['usuario'], name='auditoria_p_usuario_ba2e81_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaproducto',
            index=models.Index(fields=['codigo_material'], name='auditoria_p_codigo__24a227_idx'),
        ),
    ]
