# Generated by Django 5.0.14 on 2025-05-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asignacionid', models.AutoField(db_column='AsignacionID', primary_key=True, serialize=False)),
                ('tecnicoid', models.IntegerField(db_column='TecnicoID')),
                ('productoid', models.IntegerField(db_column='ProductoID')),
                ('cantidadasignada', models.DecimalField(db_column='CantidadAsignada', decimal_places=2, max_digits=10)),
                ('fechaasignacion', models.DateTimeField(db_column='FechaAsignacion')),
                ('fechadevolucionesperada', models.DateField(blank=True, db_column='FechaDevolucionEsperada', null=True)),
                ('estado', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Estado', max_length=20)),
            ],
            options={
                'db_table': 'Asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracionmulta',
            fields=[
                ('configuracionmultaid', models.AutoField(db_column='ConfiguracionMultaID', primary_key=True, serialize=False)),
                ('montopordia', models.DecimalField(db_column='MontoPorDia', decimal_places=2, max_digits=10)),
                ('maximodiassinmulta', models.IntegerField(db_column='MaximoDiasSinMulta')),
                ('activo', models.BooleanField(db_column='Activo')),
            ],
            options={
                'db_table': 'ConfiguracionMulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialmulta',
            fields=[
                ('historialmultaid', models.AutoField(db_column='HistorialMultaID', primary_key=True, serialize=False)),
                ('estadoanterior', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EstadoAnterior', max_length=20)),
                ('estadonuevo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EstadoNuevo', max_length=20)),
                ('fechacambio', models.DateTimeField(db_column='FechaCambio')),
                ('usuarioid', models.IntegerField(db_column='UsuarioID')),
                ('observacion', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Observacion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'HistorialMulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('multaid', models.AutoField(db_column='MultaID', primary_key=True, serialize=False)),
                ('diasretraso', models.IntegerField(db_column='DiasRetraso')),
                ('montopordia', models.DecimalField(db_column='MontoPorDia', decimal_places=2, max_digits=10)),
                ('montototal', models.DecimalField(db_column='MontoTotal', decimal_places=2, max_digits=10)),
                ('fechageneracion', models.DateTimeField(db_column='FechaGeneracion')),
                ('estadopago', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EstadoPago', max_length=20)),
                ('fechapago', models.DateTimeField(blank=True, db_column='FechaPago', null=True)),
            ],
            options={
                'db_table': 'Multa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacionid', models.AutoField(db_column='NotificacionID', primary_key=True, serialize=False)),
                ('usuarioid', models.IntegerField(db_column='UsuarioID')),
                ('mensaje', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensaje', max_length=255)),
                ('tipo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tipo', max_length=50)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('leida', models.BooleanField(db_column='Leida')),
            ],
            options={
                'db_table': 'Notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_material', models.IntegerField()),
                ('nom_producto', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('cant_existencia', models.IntegerField()),
                ('descripcion', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('stock_minimo', models.IntegerField()),
                ('stock_maximo', models.IntegerField()),
                ('categoria_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
    ]
