# Generated by Django 5.0.14 on 2025-06-06 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_tipoproducto_delete_authgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='alerta_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='categoria_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='producto.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', default=2, on_delete=django.db.models.deletion.PROTECT, to='producto.tipoproducto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('asignacion', 'Asignación a técnico')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MovimientoInventario',
                'indexes': [models.Index(fields=['fecha', 'producto'], name='MovimientoI_fecha_c49b6a_idx')],
            },
        ),
    ]
